# Use the httpd-parent image as base
FROM quay.io/redhattraining/httpd-parent
LABEL io.k8s.description="A basic Apache HTTP Server"\ io.k8s.display-name="Apache HTTP Server"\ openshift.expose-services="8080:http"\ io.openshift.tags="apache, httpd"


